# Deployment Manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: MYSQL_DATABASE
            - name: MYSQL_USER
              value: MYSQL_USER
            - name: MYSQL_PASSWORD
              value: MYSQL_RANDOM_ROOT_PASSWORD
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "1"
          image: mysql:latest
          name: mysql-container
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data  # Nome do volume no pod
      restartPolicy: Always
      volumes:
        - name: mysql-data
          hostPath:
            path: /mnt/mysql-data

---

# Service Manifest
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: db
  name: db
spec:
  selector:
    io.kompose.service: db
  ports:
    - port: 3306
      targetPort: 3306
      name: db
      protocol: TCP
status:
  loadBalancer: {}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/mysql-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mysql-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi





