# Service Manifest
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 80
      nodePort: 30000
      name: http
      protocol: TCP
  selector:
    app: wordpress
status:
  loadBalancer: {}

---

# Deployment Manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wordpress
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: wordpress
        app: wordpress
    spec:
      containers:
        - env:
            - name: WORDPRESS_DB_HOST
              value: db
            - name: WORDPRESS_DB_NAME
              value: MYSQL_DATABASE
            - name: WORDPRESS_DB_PASSWORD
              value: MYSQL_RANDOM_ROOT_PASSWORD
            - name: WORDPRESS_DB_USER
              value: MYSQL_USER
          image: wordpress:latest
          name: wordpress
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress-volume  # Nome do volume no pod
      restartPolicy: Always
      volumes:
        - name: wordpress-volume
          hostPath:
            path: /mnt/wordpress-html

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-data-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/wordpress-html

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: wordpress-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
